name: DoubleLife
version: '${project.version}'
main: me.rowanscripts.doublelife.DoubleLife
api-version: 1.19
authors: [ Rowan ]
description: A recreation of the mod/plugin used in the official Double Life series hosted by Grian!
website: https://github.com/RowwYourBoat

commands:
  doublelife:
    permission: doublelife.admin
    description: Prefix to all administrative Double Life related commands
    usage: /doublelife help
    aliases:
      - dl

permissions:
  doublelife.admin:
    default: op
    description: grants access to all administrative commands
  doublelife.nopair:
    default: false
    description: players with this permission won't be assigned to a pair